# SETUP
baseURL = "https://dlvmc.mds.mat.univie.ac.at"
relativeURLs = true
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"] # disable hugo's content that we don't need...
title = "DL-VMC" # page title -> see ./layouts/partials/head.html
googleAnalytics = "" # if needed...

[markup.goldmark.renderer]
unsafe= true

[author]
    name = "Michael Scherbela"
    email = "michael.scherbela@gmail.com"

[params]
    description = "Webpage for the mini-symposium on deep-learning-based Variational Monte Carlo, at University of Vienna from July 3-4 2023"

